version: "3"
services:
  app:
    build:
      context: .
      target: prod
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres_container
    image: postgres:15.5
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - app_postgres_vol:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  backend:

volumes:
  app_postgres_vol: