version: "3"
services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
    networks:
      - backend
    depends_on:
      - postgres
  nginx:
    container_name: nginx_container
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      - app
  postgres:
    container_name: postgres_container
    image: postgres:15.5
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /data/postgres
    volumes:
      - app_postgres_vol:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  app_postgres_vol: